version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9
    working_directory: ~/repo

    # TODO: dependency cache
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: npm ci
      - run: npm run build


