version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9
    working_directory: ~/repo

    # TODO: dependency cache
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: npm ci
      - run: npm run build
      - run: zip -r build.zip build
      - store_artifacts:
          path: ~/repo/build.zip
          destination: build
      - add_ssh_keys:
          fingerprints:
            - "23:a6:f5:f1:a9:db:50:34:8c:ab:94:e5:3a:c8:05:d7"
      - run:
          name: Deploy to server
          command: |
            ssh circleci@srv1.arthurx.space
            cd denis
            ./all.sh


